# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - oraclejdk11

# используем режим обычного пользователя для сборки проекта.
sudo: false

install: true

#script: mvn clean package -DskipTests=true

services:
  postgresql
## Изменяет текущую временную зону.
before_install:
  - export TZ=Europe/Moscow
  - date
#  # JDBC создание базы данных
  - psql -c 'create database url_shortcut;' -U postgres

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  global:
    - CODECOV_TOKEN="aadece00-b2a4-4944-9cc7-b6d5bba939e6"

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      -roman9628@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

